### ISSUE TITLE
demo?

### ISSUE THREAD

**Issue by ganySA** [fredguile/ng2-md-datatable#2]
A demo would be great......

**Comment by fredguile** [comment]
You're definitely right! Very sorry for that, I'll work on providing a small demo-app soon using @ngrx/store, as I'm currently working on something similar. Hopefully I can extract the demo-app from that with minimal effort ;)

**Comment by fredguile** [comment]
Demo is here! 
https://github.com/fredguile/ng2-md-datatable/tree/master/demo-app

**Comment by wouter-b** [comment]
Do you have a demo including @ngrx/store ?

**Comment by fredguile** [comment]
unfortunately that part is in a company project... but I think you could find valuable examples here:
<https://github.com/btroncone/ngrx-examples>

To me it doesn't change much your template. When writing the datatable, instead of looping thru an array you would loop thru an observable of something like this:

```
<ng2-md-datatable-row *ngFor="let log of logsList$ | async">
       <td>{{ log.source }}: {{ log.message }}</td>
</ng2-md-datatable-row>
```

The AsyncPipe does the job of subscribing to the Observable and rerendering the component's content when new values gets emitted.

**Comment by psk2** [comment]
@fredguile , the link you provided is not working.
https://github.com/fredguile/ng2-md-datatable/tree/master/demo-app

could you please provide us a working demo which will be more helpful.

**Comment by fredguile** [comment]
Maybe it was valid on April, 11th but not today (as the code "moves"). Have you tried here?
https://github.com/fredguile/ng2-md-datatable/tree/master/src/demo-app
