### ISSUE TITLE
How to set default value for 'Rows per page' dropdown

### ISSUE THREAD

**Issue by RohitLuthra19** [fredguile/ng2-md-datatable#20]
I set it in code but its not gets selected bydefault in dropdown in pagination control.
![screen shot 2017-04-14 at 11 53 54 pm](https://cloud.githubusercontent.com/assets/11659536/25052079/ad31ec76-216d-11e7-9cdd-76eb6f12e33a.png)

**Comment by fredguile** [comment]
There might have been a bug regarding this in versions < 1.2.3, I suggest updating to 1.2.3 at least.

And in your code, you can set the initial pagination with the attribute "itemsPerPageFirstChoice" (which must get a value that exists in the array defined in the attribute "itemsPerPageChoices").

For instance:
```
<ng2-md-datatable-pagination
  [currentPage]="1"
  [itemsPerPage]="5"
  [itemsCount]="700"
  [itemsPerPageChoices]="[5,10,15]"
  [itemsPerPageFirstChoice]="15"
  >
</ng2-md-datatable-pagination>
```

Also not 100% sure, but it's preferable to write [itemsPerPageFirstChoice]="15" and not itemsPerPageFirstChoice="15", so that the bracket makes 15 to be evaluated as a number (and not a string). 

Let me know if it works.

**Comment by RohitLuthra19** [comment]
Currently I am using version 1.3.1 which one is latest . But your suggested solution not worked for me. I have done exactly what you suggested.

**Comment by fredguile** [comment]
Maybe you want to send me a link of your code? or paste a snippet?

**Comment by RohitLuthra19** [comment]
Sorry @fredguile I was using Angular 2 not Angular 4 thats why it was not worked. So after updating to Angular4 It works. Thanks man for your great support..
