### ISSUE TITLE
Can't build your project

### ISSUE THREAD

**Issue by gtzinos** [fredguile/ng2-md-datatable#31]
Hello,
I downloaded 1.3.1version and i can't build it. It returns me this:

ERROR in MdDataTableModule is not an NgModule

**Comment by fredguile** [comment]
Hi, that's somehow linked to issue #29 and I'm currently troubleshooting it, but that's a tricky compilation issue. Not sure if that's caused by Typescript or Angular-CLI but for sure that's because metadata are lost during the build process, hence NgModule is somehow removed from the js files built in /dist. However v1.3.1 did work okay for me, that's the one I current use with AOT enabled. 

Which version of Angular are you having?

**Comment by gtzinos** [comment]
Hello,
I tryied it with both 1.3.1 and your latest version of your project. I have @angular/cli: 1.0.0. One solution maybe is to downgrade cli to beta in order to use ng init. Angular removed ng init on latest version so i can't use it to fix this issue.

**Comment by gtzinos** [comment]
Also you don't have angular-cli in devDependencies

**Comment by surfjedi** [comment]
+1 same issue here

**Comment by fredguile** [comment]
Hi guys, my apologise, there were issues in the build pipeline, but this shall normally be okay with the new release:
https://github.com/fredguile/ng2-md-datatable/releases/tag/v1.3.4

Feedback are welcome!

**Comment by gtzinos** [comment]
Don't close this issue. You demo app not works again.

**Comment by gtzinos** [comment]
To run the demo app you need to npm install in root folder and execute gulp build:components. Please add istructions in README. Also i executed npm intall in demo-app folder and ng serve. Now it returns again (ERROR in MdDataTableModule is not an NgModule)

**Comment by gtzinos** [comment]
Finally i fixed this issue. Instructions to run your demo-app:

1) npm install (root folder)
2) gulp build:components
3) npm install (/src/demo-app/)
4) gulp build:components(/src/demo-app)
