### ISSUE TITLE
Compilation failed

### ISSUE THREAD

**Issue by zengxiaoling** [fredguile/ng2-md-datatable#51]
Error: Compilation failed; Resource file not found: .... node_modules/ng2-md-datatable/mixins

but actually _mixins.sass is not mixins

**Comment by fredguile** [comment]
I'd say someone already reported that once, and it was due to a wrong release of `node-sass` if I remember well...

`_mixins.sass` do contain mixins and remember that with SASS we can import that without specifying the trailing underscore.

Since both the lib and the demo-app contain a `package-lock.json`, do you think it's worth retrying getting all dependencies using NPM >=5? You would them use the same versions as the time I compiled the whole thing...

**Comment by fredguile** [comment]
any outcome here or shall I close the ticket?

**Comment by zengxiaoling** [comment]
yes, you can.

**Comment by fredguile** [comment]
cool, I hope you finally got it to compile
